# Generated by Django 6.1.1 on 2026-10-02 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=500, unique=True)),
                ('new_path', models.CharField(max_length=500)),
                ('redirect_type', models.PositiveSmallIntegerField(choices=[(301, '301 Permanent'), (302, '302 Temporary')], default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='seo_content_object_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_seo_target')],
            },
        ),
    ]
