# Generated by Django 6.1.1 on 2026-10-02 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_category', models.CharField(blank=True, max_length=100)),
                ('page_path', models.CharField(blank=True, max_length=1000)),
                ('referrer', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_name', '-created_at'], name='analytics_event_time_idx'), models.Index(fields=['page_path'], name='analytics_page_idx')],
            },
        ),
    ]
